// NestLocal Experience 2.0 — fully synthetic, in-memory scenario engine.
// No auth, tenant lookup, cookies, localStorage, Firestore writes or provider calls.
const EL=document.getElementById('experienceRoot');
const LANG=document.getElementById('language');
const state={language:'pt',sector:null,step:0,slot:null,completed:false};
const labels={
pt:{demo:'Demonstração fictícia',eyebrow:'Viva a experiência antes de cadastrar',welcome:'O próximo serviço já começa organizado.',welcomeText:'Escolha seu setor e experimente como um pedido vira orçamento, agenda, execução e oportunidade de retorno. Sem conta, telefone, WhatsApp ou cartão.',sectorTitle:'Qual é o seu negócio?',sectorHelp:'Tudo aqui é simulado. Nenhum dado de cliente é acessado ou criado.',start:'Experimentar este setor',step1:'Pedido recebido',step2:'Orçamento preparado',step3:'Aprovação do cliente',step4:'Agendamento',step5:'Execução',step6:'Próximo serviço',request:'Solicitação',customer:'Cliente fictício',service:'Serviço',context:'O que aconteceu',source:'Origem',sourceValue:'Formulário fictício',action1:'Analisar pedido e preparar orçamento',quote:'Orçamento',scope:'Escopo do serviço',estimate:'Valor fictício calculado para o cenário',method:'Nesta demonstração, o valor vem de uma regra fixa do cenário, não de IA.',action2:'Preparar aprovação simulada',approval:'Aprovação',approvalHelp:'Agora você está no papel do cliente fictício. Escolha aprovar este orçamento.',approve:'Simular aprovação',schedule:'Agenda',scheduleHelp:'Estes horários são exemplos fictícios, não disponibilidade real.',chooseSlot:'Escolha um horário de exemplo',morning:'Próximo dia · 09:00',afternoon:'Próximo dia · 14:00',action4:'Confirmar agenda fictícia',execution:'Serviço em execução',executionHelp:'O cliente fictício aprovou e o agendamento foi simulado. Agora registre a conclusão.',action5:'Marcar execução simulada como concluída',return:'Retorno inteligente',returnHelp:'O serviço foi concluído. O NestLocal identifica uma próxima ação com base na regra de recorrência cadastrada neste exemplo. Nenhuma mensagem será enviada.',why:'Por que esta sugestão apareceu?',whyValue:'O cenário registra um serviço concluído e uma regra fictícia de retorno. Não é previsão de nova venda.',action6:'Preparar lembrete fictício',completeTitle:'Você acabou de organizar um ciclo completo.',completeText:'Da solicitação até o próximo contato, sem conectar canal algum. Estes resultados foram apenas uma simulação.',cta:'Quero usar no meu negócio',secondary:'Voltar ao início',back:'Voltar',reset:'Reiniciar experiência',progress:'Progresso',disclaimer:'Ambiente 100% fictício. Nenhuma ação real, envio, cobrança ou reserva é executada.',phase:'Etapa',of:'de',approved:'Aprovado no cenário',scheduled:'Agendado no cenário',done:'Concluído no cenário',draft:'Rascunho revisável',returnNote:'Sugestão apenas. Você decide se e quando entrar em contato.',time:'Tempo estimado',next:'Próxima etapa',price:'Valor do cenário'},
en:{demo:'Fictional demonstration',eyebrow:'Experience the value before signing up',welcome:'Your next service, already organized.',welcomeText:'Choose your trade and explore how a request turns into a quote, schedule, execution and repeat opportunity. No account, phone, WhatsApp or card.',sectorTitle:'What type of business?',sectorHelp:'Everything here is simulated. No actual customer record is accessed or created.',start:'Try this sector',step1:'New request',step2:'Quote prepared',step3:'Customer approval',step4:'Scheduling',step5:'Execution',step6:'Next service',request:'Request',customer:'Fictional customer',service:'Service',context:'What happened',source:'Source',sourceValue:'Fictional form',action1:'Review request and prepare quote',quote:'Quote',scope:'Service scope',estimate:'Fictional price calculated for this scenario',method:'The demo price follows a fixed scenario rule, not AI.',action2:'Prepare simulated approval',approval:'Approval',approvalHelp:'You are now the fictional customer. Approve this quote to continue.',approve:'Simulate approval',schedule:'Schedule',scheduleHelp:'These are example slots, not real availability.',chooseSlot:'Choose an example slot',morning:'Next day · 9:00 AM',afternoon:'Next day · 2:00 PM',action4:'Confirm fictional booking',execution:'Service in progress',executionHelp:'The fictional customer approved and the booking was simulated. Now record completion.',action5:'Mark simulated work complete',return:'Smart follow-up',returnHelp:'Work is complete. NestLocal suggests a next action using a recurrence rule in this sample. No message will be sent.',why:'Why am I seeing this?',whyValue:'This scenario records completed work and a fictional return rule. No future sale is predicted.',action6:'Prepare fictional reminder',completeTitle:'You organized a complete service cycle.',completeText:'From first request to next contact, without connecting any channel. Every outcome was simulated.',cta:'Use it for my business',secondary:'Start over',back:'Back',reset:'Reset demo',progress:'Progress',disclaimer:'100% fictional environment. No real action, message, charge or booking occurs.',phase:'Step',of:'of',approved:'Approved in simulation',scheduled:'Booked in simulation',done:'Completed in simulation',draft:'Reviewable draft',returnNote:'Suggestion only. You decide if and when to contact a customer.',time:'Estimated duration',next:'Next step',price:'Scenario price'},
es:{demo:'Demostración ficticia',eyebrow:'Descubre el valor antes de registrarte',welcome:'Tu próximo servicio, ya organizado.',welcomeText:'Elige tu sector y descubre cómo una solicitud se convierte en presupuesto, agenda, ejecución y oportunidad de retorno. Sin cuenta, teléfono, WhatsApp ni tarjeta.',sectorTitle:'¿Cuál es tu negocio?',sectorHelp:'Todo aquí es simulado. No se consulta ni se crea información de clientes reales.',start:'Probar este sector',step1:'Solicitud recibida',step2:'Presupuesto preparado',step3:'Aprobación del cliente',step4:'Agenda',step5:'Ejecución',step6:'Próximo servicio',request:'Solicitud',customer:'Cliente ficticio',service:'Servicio',context:'Qué ocurrió',source:'Origen',sourceValue:'Formulario ficticio',action1:'Revisar solicitud y preparar presupuesto',quote:'Presupuesto',scope:'Alcance del servicio',estimate:'Precio ficticio calculado para el escenario',method:'El precio de la demo sigue una regla fija, no IA.',action2:'Preparar aprobación simulada',approval:'Aprobación',approvalHelp:'Ahora eres el cliente ficticio. Aprueba este presupuesto para continuar.',approve:'Simular aprobación',schedule:'Agenda',scheduleHelp:'Estos horarios son ejemplos, no disponibilidad real.',chooseSlot:'Elige un horario de ejemplo',morning:'Día siguiente · 09:00',afternoon:'Día siguiente · 14:00',action4:'Confirmar agenda ficticia',execution:'Servicio en ejecución',executionHelp:'El cliente ficticio aprobó y se simuló la reserva. Ahora registra la finalización.',action5:'Marcar ejecución simulada como terminada',return:'Próximo contacto',returnHelp:'El servicio terminó. NestLocal sugiere una acción según una regla ficticia de recurrencia. No se enviará ningún mensaje.',why:'¿Por qué veo esta sugerencia?',whyValue:'Este escenario registra un servicio completado y una regla ficticia de retorno. No pronostica ventas.',action6:'Preparar recordatorio ficticio',completeTitle:'Organizaste un ciclo completo.',completeText:'Desde la solicitud hasta el próximo contacto, sin conectar canales. Todo fue una simulación.',cta:'Quiero usarlo en mi negocio',secondary:'Volver al inicio',back:'Volver',reset:'Reiniciar demo',progress:'Progreso',disclaimer:'Entorno 100% ficticio. No se realiza ninguna acción, envío, cobro ni reserva real.',phase:'Paso',of:'de',approved:'Aprobado en la demo',scheduled:'Agendado en la demo',done:'Finalizado en la demo',draft:'Borrador editable',returnNote:'Solo sugerencia. Tú decides si y cuándo contactar.',time:'Duración estimada',next:'Siguiente paso',price:'Precio del ejemplo'}
};
const sectors=[
{id:'climate',name:{pt:'Climatização',en:'Air conditioning',es:'Climatización'},service:{pt:'Higienização de 2 aparelhos split',en:'Cleaning of 2 split AC units',es:'Limpieza de 2 equipos split'},detail:{pt:'Limpeza preventiva residencial, acesso interno.',en:'Residential preventive cleaning, indoor access.',es:'Limpieza preventiva residencial, acceso interior.'},returnDays:180,amount:32000,duration:120,number:'NL-DEMO-101'},
{id:'cleaning',name:{pt:'Limpeza especializada',en:'Specialist cleaning',es:'Limpieza especializada'},service:{pt:'Higienização de sofá de 3 lugares',en:'Three-seat sofa deep clean',es:'Limpieza de sofá de 3 plazas'},detail:{pt:'Estofado com manchas leves, avaliação de tecido.',en:'Light stains, fabric assessment.',es:'Manchas leves, revisión del tejido.'},returnDays:180,amount:24000,duration:90,number:'NL-DEMO-102'},
{id:'pest',name:{pt:'Controle de pragas',en:'Pest control',es:'Control de plagas'},service:{pt:'Controle preventivo residencial',en:'Residential preventive pest control',es:'Control preventivo residencial'},detail:{pt:'Casa térrea, vistoria dos principais ambientes.',en:'Single-story home, inspection of main rooms.',es:'Casa de una planta, inspección de ambientes.'},returnDays:120,amount:28000,duration:90,number:'NL-DEMO-103'},
{id:'electrical',name:{pt:'Elétrica',en:'Electrical services',es:'Electricidad'},service:{pt:'Instalação de 3 luminárias',en:'Installation of three lights',es:'Instalación de tres lámparas'},detail:{pt:'Pontos já preparados; orçamento revisado no cenário.',en:'Existing wiring points; quote reviewed in the scenario.',es:'Puntos existentes; presupuesto revisado en el ejemplo.'},returnDays:365,amount:21000,duration:120,number:'NL-DEMO-104'},
{id:'general',name:{pt:'Serviços gerais',en:'General services',es:'Servicios generales'},service:{pt:'Manutenção residencial preventiva',en:'Preventive home maintenance',es:'Mantenimiento preventivo del hogar'},detail:{pt:'Pequenos reparos, escopo previamente confirmado.',en:'Small repairs with a pre-approved scope.',es:'Reparaciones menores con alcance previamente acordado.'},returnDays:180,amount:19000,duration:120,number:'NL-DEMO-105'}
];
const t=k=>(labels[state.language]||labels.pt)[k]||k;
const v=item=>item?.[state.language]||item?.pt||'';
const money=cents=>new Intl.NumberFormat(state.language==='en'?'en-US':state.language==='es'?'es-ES':'pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
function track(event){ // Minimal anonymous telemetry; no identifiers, user-entered text or cookies.
  if(!['demo_started','demo_step_completed','demo_completed','demo_to_signup'].includes(event))return;
  const payload={event,segment:state.sector?.id||'unknown',step:state.step};
  try{fetch('/api/public/demo/events',{method:'POST',credentials:'omit',headers:{'content-type':'application/json'},body:JSON.stringify(payload),keepalive:true}).catch(()=>{});}catch{}
}
function reset(){state.sector=null;state.step=0;state.slot=null;state.completed=false;render()}
const steps=['step1','step2','step3','step4','step5','step6'];
function layout(content){
  const progress=state.sector?Math.min(100,Math.round(state.step/6*100)):0;
  return '<div class="experience-wrap"><div class="intro"><span class="eyebrow">'+t('eyebrow')+'</span><h1>'+t('welcome')+'</h1><p>'+t('welcomeText')+'</p></div>'+
    '<section class="experience-layout"><div class="workspace"><div class="workspace-top"><span class="scenario-label">'+t('demo')+'</span>'+
    (state.sector?'<span class="number">'+state.sector.number+'</span>':'<span class="number">NESTLOCAL 2.0</span>')+'</div>'+
    (state.sector?'<div class="progress-shell"><div class="progress-caption"><span>'+t('progress')+'</span><strong>'+Math.min(state.step,6)+' / 6</strong></div><div class="progress-track" role="progressbar" aria-label="'+t('progress')+'" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+progress+'"><i style="width:'+progress+'%"></i></div></div>':'')+
    content+
    '<div class="foot-actions">'+(state.sector&&state.step>1&&state.step<7?'<button class="subtle-button" data-action="back">'+t('back')+'</button>':'<span></span>')+'<button class="subtle-button" data-action="reset">'+t('reset')+'</button></div></div>'+
    '<aside class="side"><span class="eyebrow">NESTLOCAL / EXPERIENCE</span><h2>'+t('progress')+'</h2><ol class="timeline">'+steps.map((k,i)=>'<li class="'+(state.sector&&state.step>i+1?'finished':state.sector&&state.step===i+1?'current':'')+'"><span class="timeline-dot">'+(i+1)+'</span><span>'+t(k)+'</span></li>').join('')+'</ol><p class="disclaimer">'+t('disclaimer')+'</p></aside></section></div>';
}
function button(label,action,disabled=false){return '<button type="button" class="primary-button" data-action="'+action+'"'+(disabled?' disabled':'')+'>'+label+'<span aria-hidden="true"> →</span></button>'}
function fact(name,value){return '<div class="fact"><span>'+name+'</span><strong>'+value+'</strong></div>'}
function panel(title,body){return '<section class="step-panel"><span class="step-overline">'+t('demo')+'</span><h2>'+title+'</h2>'+body+'</section>'}
function render(){
  document.documentElement.lang=state.language==='pt'?'pt-BR':state.language;
  document.getElementById('demoBadge').textContent=t('demo');
  LANG.value=state.language;
  const sector=state.sector;
  let content='';
  if(!sector){
    content=panel(t('sectorTitle'),'<p class="subcopy">'+t('sectorHelp')+'</p><div class="sectors">'+sectors.map((s,i)=>'<button class="sector" data-sector="'+s.id+'"><span class="sector-numeral">0'+(i+1)+'</span><strong>'+v(s.name)+'</strong><span class="sector-cta">'+t('start')+' ↗</span></button>').join('')+'</div>');
  }else if(state.step===1){
    content=panel(t('step1'),'<p class="subcopy">'+t('context')+': '+v(sector.detail)+'</p><div class="facts">'+fact(t('request'),sector.number)+fact(t('service'),v(sector.service))+fact(t('customer'),state.language==='en'?'Sample customer':state.language==='es'?'Cliente de ejemplo':'Cliente de exemplo')+fact(t('source'),t('sourceValue'))+'</div>'+button(t('action1'),'next'));
  }else if(state.step===2){
    content=panel(t('step2'),'<div class="big-price"><span>'+t('price')+'</span><strong>'+money(sector.amount)+'</strong></div><div class="facts">'+fact(t('scope'),v(sector.service))+fact(t('time'),sector.duration+' min')+'</div><p class="subcopy">'+t('method')+'</p>'+button(t('action2'),'next'));
  }else if(state.step===3){
    content=panel(t('step3'),'<p class="subcopy">'+t('approvalHelp')+'</p><div class="approval-sheet"><span>'+t('quote')+' · '+sector.number+'</span><strong>'+money(sector.amount)+'</strong><p>'+v(sector.service)+'</p></div>'+button(t('approve'),'next'));
  }else if(state.step===4){
    content=panel(t('step4'),'<div class="status"><span class="status-dot"></span>'+t('approved')+'</div><p class="subcopy">'+t('scheduleHelp')+'</p><fieldset class="slot-picker"><legend>'+t('chooseSlot')+'</legend><label class="'+(state.slot==='morning'?'selected':'')+'"><input type="radio" name="slot" value="morning" '+(state.slot==='morning'?'checked':'')+'><span>'+t('morning')+'</span></label><label class="'+(state.slot==='afternoon'?'selected':'')+'"><input type="radio" name="slot" value="afternoon" '+(state.slot==='afternoon'?'checked':'')+'><span>'+t('afternoon')+'</span></label></fieldset>'+button(t('action4'),'next',!state.slot));
  }else if(state.step===5){
    content=panel(t('step5'),'<div class="status"><span class="status-dot"></span>'+t('scheduled')+': '+t(state.slot)+'</div><p class="subcopy">'+t('executionHelp')+'</p><div class="facts">'+fact(t('service'),v(sector.service))+fact(t('price'),money(sector.amount))+'</div>'+button(t('action5'),'next'));
  }else if(state.step===6){
    content=panel(t('step6'),'<div class="status"><span class="status-dot"></span>'+t('done')+'</div><p class="subcopy">'+t('returnHelp')+'</p><div class="insight"><small>'+t('why')+'</small><p>'+t('whyValue')+'</p><strong>'+sector.returnDays+' '+(state.language==='en'?'days':state.language==='es'?'días':'dias')+'</strong></div><p class="subcopy">'+t('returnNote')+'</p>'+button(t('action6'),'next'));
  }else{
    content=panel(t('completeTitle'),'<div class="success-mark" aria-hidden="true">✓</div><p class="subcopy">'+t('completeText')+'</p><div class="status"><span class="status-dot"></span>'+t('draft')+'</div><a class="primary-button link-cta" href="https://www.millionsnest.com/apps/nestlocal/launch?returnTo=%2F" id="demoSignup">'+t('cta')+' ↗</a><button class="subtle-button wide-reset" data-action="reset">'+t('secondary')+'</button>');
  }
  EL.innerHTML=layout(content);
}
LANG.addEventListener('change',e=>{if(['pt','en','es'].includes(e.target.value)){state.language=e.target.value;render()}});
EL.addEventListener('change',e=>{if(e.target?.name==='slot'&&['morning','afternoon'].includes(e.target.value)){state.slot=e.target.value;render()}});
EL.addEventListener('click',e=>{
  const sectorButton=e.target.closest('[data-sector]');
  if(sectorButton){const s=sectors.find(x=>x.id===sectorButton.dataset.sector);if(!s)return;state.sector=s;state.step=1;state.slot=null;track('demo_started');render();return}
  const action=e.target.closest('[data-action]')?.dataset.action;
  if(action==='reset')return reset();
  if(action==='back'&&state.step>1){state.step--;render();return}
  if(action==='next'&&state.sector&&state.step>=1&&state.step<=6){
    if(state.step===4&&!state.slot)return;
    track('demo_step_completed');state.step++;if(state.step===7){state.completed=true;track('demo_completed')}render();
  }
});
document.addEventListener('click',e=>{if(e.target.closest('#demoSignup'))track('demo_to_signup')});
render();
