import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';

const cfg={apiKey:'AIzaSyAhXY8TV8qoXz8Pd2u5jFHUTVssZmi3kMs',authDomain:'millionsnest.firebaseapp.com',projectId:'millionsnest',storageBucket:'millionsnest.firebasestorage.app',messagingSenderId:'555464791734',appId:'1:555464791734:web:3059e8ac2b8089a1767817'};
const auth=getAuth(initializeApp(cfg));
const S={page:'today',lang:localStorage.getItem('nl_lang')||'pt',user:null,session:null,orgId:localStorage.getItem('nl_org')||'',data:null,loading:true,error:'',store:null,result:null,tracking:null};
const D={
pt:{today:'Hoje',requests:'Pedidos',agenda:'Agenda',services:'Serviços',automation:'Automações',page:'Minha página',login:'Entrar com Google',welcome:'Sua operação local, organizada.',loginHelp:'Use a mesma conta do MillionsNest para administrar sua empresa.',logout:'Sair',action:'Pedidos que pedem ação',open:'Receita em aberto',customers:'Clientes',conversion:'Conversão',inbox:'Caixa de entrada',empty:'Nada por aqui ainda.',setup:'Preparar NestLocal',setupHelp:'Cria um catálogo inicial em rascunho. Revise os preços antes de publicar.',create:'Criar configuração',catalog:'Catálogo',settings:'Dados da página',save:'Salvar',publish:'Publicar catálogo',draft:'Rascunho',published:'Publicado',business:'Nome da empresa',slug:'Endereço da página',coverage:'Cidades atendidas',whatsapp:'WhatsApp',price:'Preço em reais',duration:'Duração em minutos',quantity:'Quantidade máxima',new:'Novo',reviewing:'Em análise',quoted:'Orçado',scheduled:'Agendado',completed:'Concluído',cancelled:'Cancelado',publicTitle:'Solicite seu serviço',publicHelp:'Responda os dados para receber preço ou avaliação.',name:'Nome',phone:'WhatsApp',city:'Cidade',equipment:'Tipo do equipamento',access:'O acesso ao aparelho é seguro e interno?',yes:'Sim',unsure:'Não tenho certeza',note:'Observações',photos:'Fotos do equipamento ou ambiente',consent:'Autorizo o uso destes dados e fotos para analisar e atender esta solicitação.',send:'Enviar solicitação',ready:'Preço calculado',review:'Precisamos avaliar',unavailable:'Fora da área atendida',track:'Acompanhar solicitação',tracking:'Status da solicitação',copy:'Copiar link',copied:'Link copiado',loading:'Carregando…',noOrg:'Nenhuma organização disponível nesta conta.',hub:'Abrir MillionsNest',requestSent:'Solicitação enviada',selectService:'Escolha o serviço',realData:'Dados reais do Firebase'},
en:{today:'Today',requests:'Requests',agenda:'Schedule',services:'Services',automation:'Automations',page:'My page',login:'Continue with Google',welcome:'Your local operation, organized.',loginHelp:'Use your MillionsNest account to manage your business.',logout:'Sign out',action:'Requests needing action',open:'Open revenue',customers:'Customers',conversion:'Conversion',inbox:'Inbox',empty:'Nothing here yet.',setup:'Set up NestLocal',setupHelp:'Creates a starter draft catalog. Review prices before publishing.',create:'Create setup',catalog:'Catalog',settings:'Page details',save:'Save',publish:'Publish catalog',draft:'Draft',published:'Published',business:'Business name',slug:'Page address',coverage:'Covered cities',whatsapp:'WhatsApp',price:'Price in BRL',duration:'Duration in minutes',quantity:'Maximum quantity',new:'New',reviewing:'Reviewing',quoted:'Quoted',scheduled:'Scheduled',completed:'Completed',cancelled:'Cancelled',publicTitle:'Request a service',publicHelp:'Share the details to receive a price or review.',name:'Name',phone:'WhatsApp',city:'City',equipment:'Equipment type',access:'Is the equipment safely accessible indoors?',yes:'Yes',unsure:'Not sure',note:'Notes',send:'Send request',ready:'Calculated price',review:'We need to review',unavailable:'Outside coverage',track:'Track request',copy:'Copy link',copied:'Link copied',loading:'Loading…',noOrg:'No organization is available for this account.',hub:'Open MillionsNest',requestSent:'Request sent',selectService:'Choose a service',realData:'Live Firebase data'},
es:{today:'Hoy',requests:'Solicitudes',agenda:'Agenda',services:'Servicios',automation:'Automatizaciones',page:'Mi página',login:'Continuar con Google',welcome:'Tu operación local, organizada.',loginHelp:'Usa la misma cuenta de MillionsNest para administrar tu empresa.',logout:'Salir',action:'Solicitudes que requieren acción',open:'Ingresos pendientes',customers:'Clientes',conversion:'Conversión',inbox:'Bandeja de entrada',empty:'Nada por aquí todavía.',setup:'Configurar NestLocal',setupHelp:'Crea un catálogo inicial en borrador. Revisa los precios antes de publicar.',create:'Crear configuración',catalog:'Catálogo',settings:'Datos de la página',save:'Guardar',publish:'Publicar catálogo',draft:'Borrador',published:'Publicado',business:'Nombre de la empresa',slug:'Dirección de la página',coverage:'Ciudades atendidas',whatsapp:'WhatsApp',price:'Precio en BRL',duration:'Duración en minutos',quantity:'Cantidad máxima',new:'Nueva',reviewing:'En análisis',quoted:'Presupuestada',scheduled:'Agendada',completed:'Finalizada',cancelled:'Cancelada',publicTitle:'Solicita tu servicio',publicHelp:'Completa los datos para recibir un precio o evaluación.',name:'Nombre',phone:'WhatsApp',city:'Ciudad',equipment:'Tipo de equipo',access:'¿El acceso al equipo es seguro e interno?',yes:'Sí',unsure:'No estoy seguro',note:'Observaciones',send:'Enviar solicitud',ready:'Precio calculado',review:'Necesitamos evaluar',unavailable:'Fuera del área',track:'Seguir solicitud',copy:'Copiar enlace',copied:'Enlace copiado',loading:'Cargando…',noOrg:'No hay organización disponible para esta cuenta.',hub:'Abrir MillionsNest',requestSent:'Solicitud enviada',selectService:'Elige un servicio',realData:'Datos reales de Firebase'}};
Object.assign(D.pt,{address:'Endereço completo',preferredDate:'Data preferida',preferredWindow:'Período preferido',morning:'Manhã',afternoon:'Tarde',evening:'Noite',flexible:'Flexível',contact:'Chamar no WhatsApp',notPublished:'Esta página ainda não está publicada',notPublishedHelp:'Confira o endereço ou peça ao prestador o link atualizado.',back:'Voltar ao NestLocal',privacy:'Privacidade',terms:'Termos',startingAt:'a partir de'});
Object.assign(D.en,{photos:'Equipment or room photos',consent:'I authorize use of this data and photos to assess and fulfill this request.',tracking:'Request status',address:'Full address',preferredDate:'Preferred date',preferredWindow:'Preferred time',morning:'Morning',afternoon:'Afternoon',evening:'Evening',flexible:'Flexible',contact:'Message on WhatsApp',notPublished:'This page is not published yet',notPublishedHelp:'Check the address or ask the provider for an updated link.',back:'Back to NestLocal',privacy:'Privacy',terms:'Terms',startingAt:'from'});
Object.assign(D.es,{photos:'Fotos del equipo o ambiente',consent:'Autorizo el uso de estos datos y fotos para evaluar y atender esta solicitud.',tracking:'Estado de la solicitud',address:'Dirección completa',preferredDate:'Fecha preferida',preferredWindow:'Horario preferido',morning:'Mañana',afternoon:'Tarde',evening:'Noche',flexible:'Flexible',contact:'Contactar por WhatsApp',notPublished:'Esta página aún no está publicada',notPublishedHelp:'Verifica la dirección o pide al profesional el enlace actualizado.',back:'Volver a NestLocal',privacy:'Privacidad',terms:'Términos',startingAt:'desde'});
const t=k=>D[S.lang]?.[k]||D.pt[k]||k;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=c=>c==null?'—':new Intl.NumberFormat(S.lang==='pt'?'pt-BR':S.lang==='es'?'es-ES':'en-US',{style:'currency',currency:'BRL'}).format(c/100);
const labels=()=>({today:t('today'),requests:t('requests'),agenda:t('agenda'),services:t('services'),automation:t('automation'),page:t('page')});
const pathParts=()=>location.pathname.split('/').filter(Boolean);
const publicSlug=()=>{const p=pathParts();return p[0]==='s'?p[1]:p[0]};
const isPublicStore=()=>{const p=pathParts();return p.length===1&&p[0]!=='track'};
const isLegal=()=>['privacy','terms'].includes(pathParts()[0]);
const lang=()=>`<select data-lang class="lang"><option ${S.lang==='pt'?'selected':''} value="pt">PT</option><option ${S.lang==='en'?'selected':''} value="en">EN</option><option ${S.lang==='es'?'selected':''} value="es">ES</option></select>`;
const toast=m=>{const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),2400)};
async function api(path,opt={}){const id=S.user?await S.user.getIdToken():'',form=opt.body instanceof FormData;const r=await fetch(path,{...opt,headers:{...(form?{}:{'Content-Type':'application/json'}),...(id?{Authorization:`Bearer ${id}`}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||`HTTP_${r.status}`);return b}
async function openPhoto(path){const id=await S.user.getIdToken(),r=await fetch(path,{headers:{Authorization:`Bearer ${id}`}});if(!r.ok)throw Error(`HTTP_${r.status}`);const u=URL.createObjectURL(await r.blob());window.open(u,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(u),60000)}
const brand=()=>`<div class="brand"><span class="brandmark">N</span>NestLocal</div>`;
function login(){return `<main class="login-shell"><section class="login-card">${brand()}<span class="eyebrow">AI Revenue & Service OS</span><h1>${t('welcome')}</h1><p>${t('loginHelp')}</p><button class="button primary login-button" id="login">${t('login')}</button>${lang()}</section></main>`}
function loading(){return `<main class="login-shell"><section class="login-card">${brand()}<p>${t('loading')}</p></section></main>`}
function noOrg(){return `<main class="login-shell"><section class="login-card">${brand()}<h1>${t('noOrg')}</h1><a class="button primary login-button" href="https://www.millionsnest.com">${t('hub')}</a><button class="button login-button" id="logout">${t('logout')}</button></section></main>`}
function nav(){return Object.entries(labels()).map(([id,x])=>`<button data-nav="${id}" class="${S.page===id?'active':''}">${x}</button>`).join('')}
function row(r){const q=r.quote||{},ini=(r.customer?.name||'?').split(' ').map(x=>x[0]).slice(0,2).join(''),photos=(r.attachments||[]).map((_x,i)=>`<button class="button tiny" data-photo="/api/organizations/${encodeURIComponent(S.orgId)}/nestlocal/requests/${encodeURIComponent(r.id)}/photos/${i}">Foto ${i+1}</button>`).join(''),wa=String(r.customer?.phone||'').replace(/\D/g,''),when=r.preference?.date?`${r.preference.date} · ${t(r.preference.window)}`:'—';return `<details class="request"><summary><div class="avatar">${esc(ini)}</div><div><strong>${esc(r.customer?.name||'—')}</strong><p>${esc(r.serviceId)} · ${money(q.totalCents)}</p></div><span class="tag">${t(r.status)}</span></summary><div class="request-detail"><p><strong>${t('phone')}:</strong> ${esc(r.customer?.phone||'—')}</p><p><strong>${t('address')}:</strong> ${esc(r.address?.line||'—')} · ${esc(r.address?.city||r.address?.coverageCode||'—')}</p><p><strong>${t('preferredDate')}:</strong> ${esc(when)}</p><p><strong>${t('note')}:</strong> ${esc(r.note||'—')}</p>${q.reasons?.length?`<p><strong>${t('review')}:</strong> ${esc(q.reasons.join(', '))}</p>`:''}<div class="request-actions">${wa?`<a class="button primary small" target="_blank" rel="noopener" href="https://wa.me/${esc(wa)}">${t('contact')}</a>`:''}${photos}</div><select class="status-select" data-request="${esc(r.id)}">${['new','reviewing','quoted','scheduled','completed','cancelled'].map(s=>`<option ${r.status===s?'selected':''} value="${s}">${t(s)}</option>`).join('')}</select></div></details>`}
function today(){const a=S.data.requests||[],open=a.filter(x=>!['completed','cancelled'].includes(x.status)),revenue=open.reduce((n,x)=>n+(x.quote?.totalCents||0),0),priced=a.filter(x=>x.quote?.outcome==='priced').length,done=a.filter(x=>x.status==='completed').length;return `<div class="grid metrics"><article class="card metric highlight"><span>${t('action')}</span><strong>${open.length}</strong><small>${t('realData')}</small></article><article class="card metric"><span>${t('open')}</span><strong>${money(revenue)}</strong><small>${t('requests')}</small></article><article class="card metric"><span>${t('customers')}</span><strong>${S.data.customerCount||0}</strong><small>${t('realData')}</small></article><article class="card metric"><span>${t('conversion')}</span><strong>${priced?Math.round(done/priced*100):0}%</strong><small>${t('completed')}</small></article></div><article class="card"><div class="section-title"><h2>${t('inbox')}</h2><span>${a.length}</span></div>${a.length?a.slice(0,12).map(row).join(''):`<div class="empty">${t('empty')}</div>`}</article>`}
function requests(){const a=S.data.requests||[];return `<article class="card"><div class="section-title"><h2>${t('requests')}</h2><span>${a.length}</span></div>${a.length?a.map(row).join(''):`<div class="empty">${t('empty')}</div>`}</article>`}
function agenda(){const a=(S.data.requests||[]).filter(x=>x.status==='scheduled');return `<article class="card"><div class="section-title"><h2>${t('agenda')}</h2><span>${a.length}</span></div>${a.length?a.map(row).join(''):`<div class="empty">${t('empty')}</div>`}</article>`}
const setup=()=>`<article class="card setup-card"><span class="eyebrow">${t('setup')}</span><h2>${t('setup')}</h2><p class="help">${t('setupHelp')}</p><button class="button primary" id="bootstrap">${t('create')}</button></article>`;
function service(s){return `<form class="service-editor" data-service="${esc(s.id)}"><strong>${esc(s.name)}</strong><input type="hidden" name="name" value="${esc(s.name)}"><input type="hidden" name="mode" value="${esc(s.mode)}">${s.mode==='fixed'?`<label>${t('price')}<input name="price" type="number" min="1" step=".01" value="${Number(s.unitPriceCents||0)/100}"></label><label>${t('duration')}<input name="duration" type="number" min="1" value="${esc(s.durationMinutes||60)}"></label><label>${t('quantity')}<input name="max" type="number" min="1" max="10" value="${esc(s.maxQuantity||1)}"></label><button class="button small">${t('save')}</button>`:`<span class="tag review">${t('review')}</span>`}</form>`}
function services(){if(!S.data.settings)return setup();const s=S.data.settings;return `<div class="grid two"><form id="settings" class="card form-grid"><div class="section-title wide"><h2>${t('settings')}</h2><span class="tag ${s.published?'':'review'}">${s.published?t('published'):t('draft')}</span></div><label>${t('business')}<input name="business" value="${esc(s.businessName)}" required></label><label>${t('slug')}<input name="slug" value="${esc(s.slug)}" required></label><label>${t('coverage')}<input name="coverage" value="${esc((s.coverageCodes||[]).join(', '))}" required></label><label>${t('whatsapp')}<input name="whatsapp" value="${esc(s.whatsapp||'')}"></label><button class="button primary wide">${t('save')}</button></form><article class="card"><div class="section-title"><h2>${t('catalog')}</h2><button class="button primary small" id="publish">${t('publish')}</button></div>${(S.data.services||[]).map(service).join('')}</article></div>`}
function automations(){const a=(S.data.requests||[]).filter(x=>['new','quoted'].includes(x.status));return `<div class="grid two"><article class="card"><div class="section-title"><h2>${t('automation')}</h2><span>${a.length}</span></div>${a.length?a.map(x=>`<div class="slot"><div class="avatar">${esc((x.customer?.name||'?')[0])}</div><div><strong>${esc(x.customer?.name)}</strong><span>${x.status==='quoted'?'Follow-up':'Revisar pedido'}</span></div></div>`).join(''):`<div class="empty">${t('empty')}</div>`}</article><article class="card"><div class="notice">WhatsApp oficial: próxima integração. As sugestões atuais usam somente dados reais.</div></article></div>`}
function page(){if(!S.data.settings)return setup();const s=S.data.settings,u=`${location.origin}/${s.slug}`;return `<article class="card"><span class="eyebrow">${s.published?t('published'):t('draft')}</span><h2>${esc(s.businessName)}</h2><div class="public-link"><code>${esc(u)}</code><button class="button small" data-copy="${esc(u)}">${t('copy')}</button></div>${s.published?`<a class="button primary" target="_blank" href="/${esc(s.slug)}">${t('page')}</a>`:`<div class="notice">${t('setupHelp')}</div>`}</article>`}
function shell(){const C={today,requests,agenda,services,automation,page}[S.page]();return `<div class="shell"><aside class="sidebar">${brand()}<nav class="nav">${nav()}</nav><div class="sidebar-foot"><strong>${esc(S.data.organization?.name)}</strong><p>${S.data.settings?.published?t('published'):t('draft')}</p></div></aside><main class="main"><header class="topbar"><div><span class="eyebrow">${t('realData')}</span><h1>${labels()[S.page]}</h1></div><div class="top-actions"><select id="org" class="field compact">${S.session.organizations.map(o=>`<option ${o.id===S.orgId?'selected':''} value="${esc(o.id)}">${esc(o.name)}</option>`).join('')}</select>${lang()}<button class="button small" id="logout">${t('logout')}</button></div></header><section class="page active">${C}</section></main><nav class="bottom-nav">${nav()}</nav></div>`}
function publicView(){if(S.loading)return loading();if(S.error)return `<main class="public-shell"><section class="public-card">${brand()}<h1>${esc(S.error)}</h1></section></main>`;if(S.tracking){const q=S.tracking.quote||{};return `<main class="public-shell"><section class="public-card">${brand()}<span class="eyebrow">${t('tracking')}</span><h1>${t(S.tracking.status)}</h1>${q.totalCents!=null?`<div class="result-price">${money(q.totalCents)}</div>`:''}<p>${esc(S.tracking.serviceId)} · ${esc(S.tracking.quantity)}</p></section></main>`}if(S.result){const q=S.result.quote,track=`${location.origin}/track/${S.result.requestId}?token=${encodeURIComponent(S.result.trackingToken)}`;return `<main class="public-shell"><section class="public-card"><span class="tag">${t('requestSent')}</span><h1>${q.outcome==='priced'?t('ready'):q.outcome==='unavailable'?t('unavailable'):t('review')}</h1>${q.totalCents!=null?`<div class="result-price">${money(q.totalCents)}</div>`:''}<a class="button primary" href="${esc(track)}">${t('track')}</a></section></main>`}const x=S.store;return `<main class="public-shell"><section class="public-card wide-public"><div class="public-brand">${brand()}${lang()}</div><span class="eyebrow">NestLocal</span><h1>${t('publicTitle')}</h1><p>${t('publicHelp')}</p><form id="public" class="form-grid"><label class="wide">${t('selectService')}<select name="serviceId">${x.services.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}${s.mode==='fixed'?` · ${money(s.unitPriceCents)}`:''}</option>`).join('')}</select></label><label>${t('name')}<input name="name" required></label><label>${t('phone')}<input name="phone" required inputmode="tel"></label><label>${t('city')}<select name="coverageCode">${x.store.coverageCodes.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><label>${t('quantity')}<input name="quantity" type="number" min="1" max="10" value="1"></label><label>${t('equipment')}<select name="equipmentType"><option value="split">Split</option><option value="other">Outro</option></select></label><label>${t('access')}<select name="safeAccess"><option value="true">${t('yes')}</option><option value="false">${t('unsure')}</option></select></label><label class="wide">${t('note')}<textarea name="note" rows="3"></textarea></label><label class="wide">${t('photos')}<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="wide consent"><input name="acceptedTerms" type="checkbox" required> ${t('consent')}</label><button class="button primary wide">${t('send')}</button></form></section></main>`}
function publicViewV2(){
  if(S.loading)return loading();
  if(S.error)return `<main class="public-shell"><section class="public-card">${brand()}<span class="eyebrow">404</span><h1>${t('notPublished')}</h1><p>${t('notPublishedHelp')}</p><a class="button primary" href="/">${t('back')}</a></section></main>`;
  if(S.tracking){const q=S.tracking.quote||{};return `<main class="public-shell"><section class="public-card">${brand()}<span class="eyebrow">${t('tracking')}</span><h1>${t(S.tracking.status)}</h1>${q.totalCents!=null?`<div class="result-price">${money(q.totalCents)}</div>`:''}<p>${esc(S.tracking.serviceId)} · ${esc(S.tracking.quantity)}</p></section></main>`}
  if(S.result){const q=S.result.quote,track=`${location.origin}/track/${S.result.requestId}?token=${encodeURIComponent(S.result.trackingToken)}`,wa=String(S.store?.store?.whatsapp||'').replace(/\D/g,''),msg=encodeURIComponent(`Olá! Acabei de enviar o pedido ${S.result.requestId} pelo NestLocal.`);return `<main class="public-shell"><section class="public-card"><span class="tag">${t('requestSent')}</span><h1>${q.outcome==='priced'?t('ready'):q.outcome==='unavailable'?t('unavailable'):t('review')}</h1>${q.totalCents!=null?`<div class="result-price">${money(q.totalCents)}</div>`:''}<div class="result-actions">${wa?`<a class="button primary" target="_blank" rel="noopener" href="https://wa.me/${esc(wa)}?text=${msg}">${t('contact')}</a>`:''}<a class="button" href="${esc(track)}">${t('track')}</a></div></section></main>`}
  const x=S.store,today=new Date().toISOString().slice(0,10);return `<main class="public-shell"><section class="public-card wide-public"><div class="public-brand">${brand()}${lang()}</div><span class="eyebrow">${esc(x.store.businessName)}</span><h1>${t('publicTitle')}</h1><p>${t('publicHelp')}</p><form id="public" class="form-grid"><label class="wide">${t('selectService')}<select name="serviceId">${x.services.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}${s.mode==='fixed'?` · ${t('startingAt')} ${money(s.unitPriceCents)}`:''}</option>`).join('')}</select></label><label>${t('name')}<input name="name" autocomplete="name" required></label><label>${t('phone')}<input name="phone" autocomplete="tel" required inputmode="tel"></label><label>${t('city')}<select name="coverageCode">${x.store.coverageCodes.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><label>${t('quantity')}<input name="quantity" type="number" min="1" max="10" value="1"></label><label class="wide">${t('address')}<input name="addressLine" autocomplete="street-address" required minlength="5"></label><label>${t('preferredDate')}<input name="preferredDate" type="date" min="${today}" required></label><label>${t('preferredWindow')}<select name="preferredWindow"><option value="morning">${t('morning')}</option><option value="afternoon">${t('afternoon')}</option><option value="evening">${t('evening')}</option><option value="flexible">${t('flexible')}</option></select></label><label>${t('equipment')}<select name="equipmentType"><option value="split">Split</option><option value="other">Outro</option></select></label><label>${t('access')}<select name="safeAccess"><option value="true">${t('yes')}</option><option value="false">${t('unsure')}</option></select></label><label class="wide">${t('note')}<textarea name="note" rows="3"></textarea></label><label class="wide">${t('photos')}<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="wide consent"><input name="acceptedTerms" type="checkbox" required><span>${t('consent')} <a href="/privacy" target="_blank">${t('privacy')}</a> · <a href="/terms" target="_blank">${t('terms')}</a></span></label><button class="button primary wide">${t('send')}</button></form></section></main>`
}
function legalView(){const privacy=pathParts()[0]==='privacy';return `<main class="public-shell"><article class="public-card wide-public">${brand()}<span class="eyebrow">NestLocal</span><h1>${privacy?t('privacy'):t('terms')}</h1>${privacy?`<p>Os dados informados são enviados ao prestador exibido na página para elaborar orçamento, entrar em contato e executar o serviço. Fotos e solicitações ficam armazenadas com acesso restrito. Para consultar, corrigir ou pedir a exclusão dos dados, contate o prestador pelo canal informado na página do serviço. Não vendemos os dados do pedido.</p><p>O prestador é responsável pelo atendimento e pelo tratamento dos dados de seus clientes. A MillionsNest fornece a infraestrutura tecnológica.</p>`:`<p>O NestLocal facilita a solicitação de serviços e a estimativa inicial de preço. O valor pode depender das informações enviadas e de avaliação técnica. Agendamento e execução só ficam confirmados após aceite do prestador.</p><p>O serviço técnico é prestado pela empresa identificada na página pública, que responde por orçamento final, execução, garantias e tributos aplicáveis.</p>`}<a class="button" href="/">${t('back')}</a></article></main>`}
function render(){const root=document.querySelector('#app');if(isLegal())root.innerHTML=legalView();else if(isPublicStore()||location.pathname.startsWith('/s/')||location.pathname.startsWith('/track/'))root.innerHTML=publicViewV2();else if(S.loading)root.innerHTML=loading();else if(!S.user)root.innerHTML=login();else if(!S.session?.organizations.length)root.innerHTML=noOrg();else root.innerHTML=shell();bind()}
async function loadData(){S.data=await api(`/api/organizations/${encodeURIComponent(S.orgId)}/nestlocal`)}
async function loadSession(){S.loading=true;render();try{S.session=await api('/api/session');if(!S.session.organizations.some(x=>x.id===S.orgId))S.orgId=S.session.organizations[0]?.id||'';if(S.orgId){localStorage.setItem('nl_org',S.orgId);await loadData()}}catch(e){S.error=e.message}S.loading=false;render()}
async function loadPublic(){try{S.store=await api(`/api/public/stores/${encodeURIComponent(publicSlug())}`)}catch(e){S.error=e.message}S.loading=false;render()}
async function loadTracking(){try{S.tracking=await api(`/api/public/requests/${encodeURIComponent(pathParts()[1])}?token=${encodeURIComponent(new URLSearchParams(location.search).get('token')||'')}`)}catch(e){S.error=e.message}S.loading=false;render()}
function bind(){
  document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{S.page=x.dataset.nav;render()});
  document.querySelectorAll('[data-lang]').forEach(x=>x.onchange=()=>{S.lang=x.value;localStorage.setItem('nl_lang',S.lang);render()});
  document.querySelector('#login')?.addEventListener('click',()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(e=>toast(e.message)));
  document.querySelector('#logout')?.addEventListener('click',()=>signOut(auth));
  document.querySelector('#org')?.addEventListener('change',async e=>{S.orgId=e.target.value;localStorage.setItem('nl_org',S.orgId);S.loading=true;render();await loadData();S.loading=false;render()});
  document.querySelector('#bootstrap')?.addEventListener('click',async()=>{await api(`/api/organizations/${S.orgId}/nestlocal/bootstrap`,{method:'POST',body:'{}'});await loadData();render()});
  document.querySelector('#settings')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api(`/api/organizations/${S.orgId}/nestlocal/settings`,{method:'PUT',body:JSON.stringify({businessName:f.get('business'),slug:f.get('slug'),coverageCodes:String(f.get('coverage')).split(',').map(x=>x.trim()),whatsapp:f.get('whatsapp'),validForMinutes:30})});await loadData();render();toast(t('save'))});
  document.querySelectorAll('[data-service]').forEach(x=>x.onsubmit=async e=>{e.preventDefault();const f=new FormData(x);await api(`/api/organizations/${S.orgId}/nestlocal/services/${x.dataset.service}`,{method:'PUT',body:JSON.stringify({name:f.get('name'),mode:f.get('mode'),unitPriceCents:Math.round(Number(f.get('price'))*100),durationMinutes:Number(f.get('duration')),maxQuantity:Number(f.get('max')),equipmentTypes:['split'],inclusions:'Incluído conforme descrição',exclusions:'Peças e serviços adicionais'})});await loadData();render();toast(t('save'))});
  document.querySelector('#publish')?.addEventListener('click',async()=>{await api(`/api/organizations/${S.orgId}/nestlocal/publish`,{method:'POST',body:'{}'});await loadData();render();toast(t('published'))});
  document.querySelectorAll('[data-request]').forEach(x=>x.onchange=async()=>{await api(`/api/organizations/${S.orgId}/nestlocal/requests/${x.dataset.request}`,{method:'PATCH',body:JSON.stringify({status:x.value})});await loadData();render()});
  document.querySelectorAll('[data-copy]').forEach(x=>x.onclick=async()=>{await navigator.clipboard.writeText(x.dataset.copy);toast(t('copied'))});
  document.querySelectorAll('[data-photo]').forEach(x=>x.onclick=()=>openPhoto(x.dataset.photo).catch(e=>toast(e.message)));
  document.querySelector('#public')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type="submit"],button:not([type])'),f=new FormData(form),photos=[...(form.elements.photos?.files||[])],b=Object.fromEntries(f);delete b.photos;b.quantity=Number(b.quantity);b.safeAccess=b.safeAccess==='true';b.acceptedTerms=f.get('acceptedTerms')==='on';b.city=b.coverageCode;button.disabled=true;try{S.result=await api(`/api/public/stores/${encodeURIComponent(publicSlug())}/requests`,{method:'POST',body:JSON.stringify(b)});if(photos.length){const uploads=new FormData();photos.slice(0,5).forEach(file=>uploads.append('photos',file));try{await api(`/api/public/requests/${S.result.requestId}/photos?token=${encodeURIComponent(S.result.trackingToken)}`,{method:'POST',body:uploads})}catch(err){toast(`Pedido salvo; fotos não enviadas: ${err.message}`)}}render()}catch(err){button.disabled=false;toast(err.message)}})
}
if(isLegal()){S.loading=false;render()}else if(isPublicStore()||location.pathname.startsWith('/s/'))loadPublic();else if(location.pathname.startsWith('/track/'))loadTracking();else onAuthStateChanged(auth,u=>{S.user=u;S.error='';if(u)loadSession();else{S.session=null;S.data=null;S.loading=false;render()}});
